//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness
{
    ///<summary></summary>
    public class UpdateTemplateResponse
    {

    }
}
